server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.156.101.153:3306/todolist
    username: root
    password: mz1874
mybatis:
  type-aliases-package: com.mz.todolist.mapper
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
